# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sde-sant <sde-sant@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/23 11:49:51 by sde-sant          #+#    #+#              #
#    Updated: 2022/09/23 12:11:18 by sde-sant         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CFLAGS += -Wall -Wextra -Werror

FILES = ft_atoi \
		ft_bzero \
		ft_calloc \
		ft_isalnum \
		ft_isalpha \
		ft_isascii \
		ft_isdigit \
		ft_isprint \
		ft_memchr \
		ft_memcmp \
		ft_memcyp \
		ft_memmove \
		ft_memset \
		ft_strchr \
		ft_strcmp \
		ft_strdup \
		ft_strlcpy \
		ft_strlen \
		ft_strnstr \
		ft_strrchr \
		ft_tolower \
		ft_toupper
